### ISSUE TITLE
fix approve expenses 

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#120]
Host is getting this error when trying to approve an expense. 

<img width="1280" alt="screen shot 2016-06-08 at 2 04 18 pm" src="https://cloud.githubusercontent.com/assets/3671070/15904748/39a32a90-2d80-11e6-8449-5b1ee920751b.png">

**Comment by sedubois** [comment]
Did you spot API error logs for this? And let's finish this before fixing (or maybe already even fixed in new code, who knows): https://github.com/OpenCollective/OpenCollective/issues/104

**Comment by asood123** [comment]
I can reproduce this. No additional info in api logs. It's failing one of
the middleware checks. Let's get new expense code live today and we'll come
back to this.

**Comment by asood123** [comment]
This should also be fixed as part of the migration. Pls reopen if we still see this issue.
