### ISSUE TITLE
Avatar not working

### ISSUE THREAD

**Issue by sebsheep** [opencollective/opencollective#2245]
I've sent an avatar for my collective at the route https://opencollective.com/elm-france/edit/images .

![image](https://user-images.githubusercontent.com/6839698/61185838-ef642d80-a65d-11e9-8114-2eb287317cd7.png)

This avatar is not displayed on the home page of my collective:
![image](https://user-images.githubusercontent.com/6839698/61185821-d491b900-a65d-11e9-9b12-5cfa3ea4052c.png)

Even worse, it is displayed as "broken image" on the event page : 
![image](https://user-images.githubusercontent.com/6839698/61185858-2a666100-a65e-11e9-9a77-71ee68bc470a.png)
(for this page - https://opencollective.com/elm-france/events/hackathon-elm-france-50136ev - , the link in the `img` tags is https://images.opencollective.com/hackathon-elm-france-50136ev/logo.png )

**Expected behaviour**
See the logo :)

**Comment by znarf** [comment]
Thank you for reporting.

1) Is a recent cache issue, it can take up to 2 hours for the image to refresh, that should not be the case, we're on it
2) Is also an issue introduced by a recent release, we're also on it

**Comment by alanna** [comment]
FYI we have got several support requests about this, and I just ran into it myself when updating OSC's avatar on its page.

**Comment by znarf** [comment]
Fix coming, this is a priority.

**Comment by znarf** [comment]
Fixed in https://github.com/opencollective/opencollective-frontend/pull/2199 and https://github.com/opencollective/opencollective-images/pull/85

**Comment by alanna** [comment]
We are still getting reports of avatars not updating through support. Should this be reopened?

**Comment by znarf** [comment]
This should be corrected by https://github.com/opencollective/opencollective-frontend/pull/2086

**Comment by dabit3** [comment]
Hey, created a new account for my organization. Would like to contribute to a couple of projects but this is kind of a blocker as my personal avatar is there, not representative of my org :/

**Comment by znarf** [comment]
@dabit3 Until we ship a fix, it's 2 hours caching maximum. So after waiting 2 hours, the image should be up to date for everyone. Fix is coming soon.
