### ISSUE TITLE
Tax form completed but not received

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2540]
See the expense comments for details: https://opencollective.com/gosublime/expenses/10024

@znarf  looked into it and said

> Might be a bit of a mess because he changed his email and that is not something supported.

What do we do in this case? We need the tax form he submitted to be associated to that user profile in our system.

**Comment by znarf** [comment]
The implementation needs to be revamped to track users through the process with their Open Collective id and not with their email.

**Comment by alanna** [comment]
@znarf what is the update on this? The user is chasing us and the system is still saying he hasn't submitted the form when he has. We can't just close the issue and leave the user hanging.

**Comment by znarf** [comment]
I shared with you long time ago the details about this case. From there, I think we can download the submitted tax form. After that, I'm not sure, suggestions?

**Comment by znarf** [comment]
I now fixed the root issue and this case should not be reproducible anymore.

**Comment by alanna** [comment]
Unfortunately the issue is not resolved. The system still thinks this user has not submitted the form, and he's not able to resubmit it.

![Screen Shot 2019-11-05 at 1 11 52 PM](https://user-images.githubusercontent.com/5498878/68168527-e660e880-ffcd-11e9-80d3-682356536a56.png)
![Screen Shot 2019-11-05 at 1 10 36 PM](https://user-images.githubusercontent.com/5498878/68168528-e660e880-ffcd-11e9-8295-4578d3ac8f32.png)

**Comment by alanna** [comment]
OK I was able to finally track down the solution in a Slack message from @znarf - we got the file. I have added it to the others to be uploaded manually at some point soon. And I manually marked it as received in Forest for this user.
