### ISSUE TITLE
Unable to set correct currency for host and its Collective

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3148]
I just set up [OCNZ](https://opencollective.com/ocnz) fiscal host. At no point in the setup process did it ask me what currency to use. It seems to have defaulted to USD. Now I can't see a way to change it to NZD. I also created the [host Collective](https://opencollective.com/ocnz-ltd) and it is defaulting to USD when it needs to be NZD. 

Am I missing something here? If not, then the host creation flow definitely needs to include currency selection as part of the setup.

**Comment by alanna** [comment]
I connected Stripe and it switched to NZD, so my immediate problem is solved.

However, now that we allow all hosts to use bank transfers and not have Stripe, we need a better solution for setting the currency.

**Comment by znarf** [comment]
Current work:

* Display Currency in the settings for all profiles
* Disable edition of Currency for Active Collectives/Funds and Fiscal Hosts
* When connecting a Manual Bank Account
  * Default to settings Currency, if changed it will update settings. 
  * Not possible to change currency if Stripe is connected
* When connecting Stripe
  * Update currency to Stripe's default currency
* Any attempt at changing currency should fail if Transactions are already recorded

It's overall a bit touchy but should be better that what we have today.

**Comment by znarf** [comment]
We can still have a difference between Stripe default currency which is bad for consistency of the ledger.
https://opencollective-metabase.herokuapp.com/dashboard/16
