### ISSUE TITLE
Failed onboarding experience

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3424]
I just had my first Collective sign up for the OCNZ host. It was a friend of mine so I was walking her through the whole process, but even still she hit so many barriers and snags and it was really disheartening. 

First, the good: she went through the process of creating a Collective and applying to host just fine. Yay. But then she got stuck.

The problems:

1. She created an event, but the default ticket tier was a free ticket for whatever reason (I think?). She was very confused because she was trying to go through the payment process for it and it wasn't showing any payment options. She ended up at this screen, which didn't give her any helpful information:

<img width="278" alt="Screen Shot 2020-08-23 at 7 48 28 PM" src="https://user-images.githubusercontent.com/5498878/90973819-adecc400-e579-11ea-9162-7b7b6a754ce6.png">

I tried to troubleshoot, but she's a brand new user, so she has no idea about how tickets are tiers or if she created a free tier with no payment methods or what. I looked at the event and tried to contribute myself and got the same error.  

I think what's going on is it's a free ticket, but then she typed in an amount when going through the checkout process, or something like that? It's not clear. If it's a free ticket it should not let you type in an amount. If it's the default ticket tier, why is it free? It would be better to have no ticket tiers created by default than have a broken one. At least then, the default donation tier would be the only one showing on the event page, and that would at least work for payments.

2. So I asked her to add me as an admin so I could try to fix it myself, but that also failed. 

First, she couldn't find the core contributors section in settings at all. It's not clear at all how you make someone an admin of an event, which is by making someone an admin of the parent Collective. I had to work out the URL of her main Collective and add the /edit/members part on the end of it and send that to her to even get her to the right screen.

Then she gets to the screen, finds my profile, and it seems all good, but I still can't get into the settings because she hadn't clicked `save` at the bottom of the screen. The save button on the core contributors settings screen is below the fold, and she was also simultaneously running into #2322, which is closed but hasn't actually been fixed.

It still looks like this, with a big `add core contributor` button appearing above the fold and the `save` button below it, so of course you're going to click the first button because you're there to add a contributor!

<img width="924" alt="Screen Shot 2020-08-23 at 8 06 25 PM" src="https://user-images.githubusercontent.com/5498878/90974217-2a34d680-e57d-11ea-8e86-c008802f555f.png">

Finally, we got past that, but *then* she tells me the actual save button is disabled! She also tells me she's trying to do all this on her phone. So I don't even know at this point. Maybe it's broken on phones?

Now she's spent all this time just trying to activate a payable ticket for her event and it's still not working for her and I can't help fix it. I'm going to get on a call with her and screenshare in order to fix it, but we really need to improve the experience so it's not this hard.

I know I should break this all down into actionable issues, but I'm feeling too defeated to think all that through right now.

**Comment by Betree** [comment]
Some things we can already extract from that:

> She was very confused because she was trying to go through the payment process for it and it wasn't showing any payment options

There's a bug here, if we try to add a custom amount on a free tier it indeed shows no payment option.

> First, she couldn't find the core contributors section in settings at all. It's not clear at all how you make someone an admin of an event, which is by making someone an admin of the parent Collective.

Events should display the `Core Contributors` section in the settings.

> The save button on the core contributors settings screen is below the fold, and she was also simultaneously running into #2322, which is closed but hasn't actually been fixed.

While the underlying UX issue described in #2322 may still be there, I was not able to reproduce the bug described - I can still remove "empty" core contributor entries.

![Peek 2020-08-24 07-46](https://user-images.githubusercontent.com/1556356/91008124-f8079100-e5dd-11ea-9306-12f1ef771db8.gif)

**Comment by znarf** [comment]
> if we try to add a custom amount on a free tier it indeed shows no payment option. 

@Betree We should not be allowed to add an amount if the Ticket has a "fixed" free amount. It's a bug that should be solved in https://github.com/opencollective/opencollective-frontend/pull/4902

**Comment by alanna** [comment]
Thanks guys. I got added as an admin and was able to fix the immediate problems she was having. Hopefully these other fixes can help make the experience better in the future. Luckily she was understanding about it and is sticking with us!

> While the underlying UX issue described in #2322 may still be there, I was not able to reproduce the bug described - I can still remove "empty" core contributor entries.

Yes sorry I was unclear. I was referring to the UX issue.

**Comment by alanna** [comment]
Everything has been moved to individual issues, so I'll close this, but it looks like many of those individual issues are still not fixed.

**Comment by Betree** [comment]
https://github.com/opencollective/opencollective/issues/3426 was not updated in time but it's fixed. So the only issue left from what was reported here seems to be https://github.com/opencollective/opencollective/issues/3427
