### ISSUE TITLE
New Tweet on view doesn't look good with the logo – Twitter Cards issue?

### ISSUE THREAD

**Issue by robnyman** [opencollective/opencollective#4014]
**Describe the bug**
If I create a new tweet pointing to a blog post on Open Collective, the link preview pulls the logo and just blows it up out of proportion. 
It also doesn't include the title of the blog post itself in the preview, but that might be solved through https://github.com/opencollective/opencollective/issues/4013

**To Reproduce**
1. Go to twitter.com
2. Create new tweet
3. Enter an Open Collective website URL
4. See link preview with too big logo

**Expected behavior**
To have a logo view adapted to the Twitter link preview

**Screenshots**
See attached screenshot for current experience.
<img width="589" alt="Tweet" src="https://user-images.githubusercontent.com/63856/108986118-171cd380-7692-11eb-8ffb-6824e3df4788.png">

**Comment by Betree** [comment]
https://github.com/opencollective/opencollective/issues/2660 could help to resolve this issue

**Comment by Betree** [comment]
In https://github.com/opencollective/opencollective-frontend/pull/6041 we've fixed the title and added the post body as a "description" meta, which should enrich a bit this preview.

![image](https://user-images.githubusercontent.com/1556356/111124484-da494b80-8570-11eb-9ee4-b06df53e882b.png)

Now about the image, https://github.com/opencollective/opencollective/issues/2660 sounds like the proper way to solve this. We do not have an ETA for it yet, but there might be a quick hack to solve the issue for you in the meantime: if you [set a cover image](https://docs.opencollective.com/help/collectives/customize-collective#set-cover-image) for your collective, it will be used in share previews instead of the logo.

**Comment by robnyman** [comment]
Thanks for the update! I can see that the post title is in the page title for blog posts now, which is great!
However, if I start a new tweet the issue remains. It just pulls the the name of the Collective.

<img width="582" alt="New-tweet" src="https://user-images.githubusercontent.com/63856/111126060-90f9fb80-8572-11eb-9606-a8c3786588a4.png">

I assume that might be related to Twitter cards or similar?

And agree #2606 is likely the solution to the other issue.

**Comment by Betree** [comment]
I think that's because of Twitter's cache, I just tried with https://cards-dev.twitter.com/validator with `https://opencollective.com/open-web-docs/updates/introducing-open-web-docs` and it seems to have the proper info (this tool is useful to refresh Twitter's cache).

![image](https://user-images.githubusercontent.com/1556356/111126915-8429d780-8573-11eb-93ca-ab5759810529.png)

**Comment by robnyman** [comment]
Interesting!
Ok, I'll wait a day or two to see that the changes propagate out properly
on their side.

Thanks!

**Comment by robnyman** [comment]
Now the title thing works for new tweets, it was just a caching issue on their side, apparently! 🎉

**Comment by Betree** [comment]
@robnyman I've just opened another issue to propose a different way to resolve this issue: https://github.com/opencollective/opencollective/issues/4098

**Comment by robnyman** [comment]
Thanks for the update!
