### ISSUE TITLE
Errors when becoming a host of a collective

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#482]
For new collective: 

1) created collective in /create and intentionally added the host email address (host+c6@opencollective.org)
2) then went to user table to find the user with that email. Looked for the collectiveID for that user (collectiveID=8945)
4) Went to the collectives table and looked for the collectiveID of the collective I created. (id=8944)
5) went to members table searched for collectiveID and role=HOST. Replaced membersCollectiveId (host+other) collectiveid=8674 with (host+c6) 8945
6) Went back to collective table and replaced the hostCollectiveId with (host+c6) 8945
7) Went to the collective url /edit#connectedAccounts and hit on connect Stripe. Stripe is connected. 

Issues: 
- [x] can't see function to connect paypal 
- [x] can't see Add Funds in /expenses

**Comment by xdamman** [comment]
I just pushed a fix to allow all admins of a host to approve and pay.
Let me know how that goes.

Btw, it's not /edit/connectedAccounts but /edit#connectedAccounts

For Paypal, you should now be able to see the prompt to connect it.

**Comment by piamancini** [comment]
@xdamman I still can't see the paypal prompt to connect. I'm looking in connectedAccounts on the collective. https://opencollective.com/newopensourcecollective/edit#connectedAccounts

**Comment by piamancini** [comment]
Also can't see the add funds feature in https://opencollective.com/newopensourcecollective/expenses 
In both cases I'm logged in with host+c6 that is set as HOST in the members table (plus is the email I used to create the collective.

**Comment by xdamman** [comment]
Can we close this issue?
The only remaining issue as far as I'm concerned is being able to connect PayPal when logged in as an admin of the host collective (right now you need to be logged in as the host to do that, but once done any admin can pay using that payment method)

**Comment by piamancini** [comment]
by host you mean the UserID of the host collective?

**Comment by piamancini** [comment]
We can't close it yet as per our chat this morning. 
Also: When I am logged in with my gmail, as a core contributor of open source collective I can manually add funds to the collective, but the Pay button doesn't show up.

**Comment by piamancini** [comment]
closing this issue as it's now part of a larger conversation about hosts #497
