### ISSUE TITLE
Default Start and End Dates are not Registered for Event Unless they are Changed

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5011]
This I noticed while working on another issue. It seems that when we create an event the default dates for start and end time are not sent to API unless we do changes to those dates. Here's an illustration of that, 

![dates-default](https://user-images.githubusercontent.com/12435965/144479152-623434de-aedc-49e5-b402-af09c8f88409.gif)

As we can see the default start date is not shown. And indeed the dates are only set on front-end if the dates are changed. 

https://github.com/opencollective/opencollective-frontend/blob/33267965ff4ae21d87743cbb6e82d026d7f0f652/components/EditEventForm.js#L217

We need to make sure the initial values are set properly on front-end. 🤔

**Comment by znarf** [comment]
@SudharakaP Isn't that fixed in the PR we're working on?

**Comment by SudharakaP** [comment]
> @SudharakaP Isn't that fixed in the PR we're working on?

No it wasn't fixed there. I initially tried to fix it there but this is another issue that wasn't related so I thought I'll do it separately.

**Comment by znarf** [comment]
@SudharakaP If that's still relevant, candidate for https://github.com/opencollective/opencollective/issues/5084?

**Comment by SudharakaP** [comment]
@znarf : Sorry, it seems that this is already fixed as per our changes with the `datetime-local`; not sure exactly which PR impacted this but when I test this now it's working fine. Hence I am closing this.
