### ISSUE TITLE
Host not showing Collective

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5165]
https://opencollective.com/yofbrc_collective is hosted by https://opencollective.com/yofbrc but it's not showing on the host page.
<img width="688" alt="Screen Shot 2022-01-30 at 10 01 47 PM" src="https://user-images.githubusercontent.com/5498878/151693425-7408fee1-3c8e-4c68-9df3-cf39b0d18f10.png">

<img width="818" alt="Screen Shot 2022-01-30 at 10 02 44 PM" src="https://user-images.githubusercontent.com/5498878/151693449-864cb4e1-993e-4e2b-9efe-968b9129cc95.png">

**Comment by alanna** [comment]
I just realised this is affecting other hosts, like Gift Collective:

![Screen Shot 2022-01-31 at 2 21 14 PM](https://user-images.githubusercontent.com/5498878/151726868-d3b6bc89-af0e-42fe-98da-a72e9490ea01.png)

And OCNZ

![Screen Shot 2022-01-31 at 2 22 37 PM](https://user-images.githubusercontent.com/5498878/151726909-9f9bb85a-ccac-44de-9878-3551038307e6.png)

However OSC and OCF do not appear to be affected.

**Comment by alanna** [comment]
I'm adding the P1 label because this is affecting multiple hosts and it's right on their front pages

**Comment by jfdh** [comment]
OCEU

![OCEU](https://user-images.githubusercontent.com/30813303/151769494-dca6076f-7842-49d3-bcbf-5e099659223b.png)

**Comment by Betree** [comment]
@jfdh The fix hasn't been deployed yet, I'll do it this morning

**Comment by Betree** [comment]
Fix deployed

**Comment by jfdh** [comment]
The issue still appears on OCEU's homepage since yesterday (worked fine for one week) @Betree

**Comment by Betree** [comment]
@jfdh Thanks for the info, I'm currently investigating https://github.com/opencollective/opencollective/issues/5202. I think both issues come from the same place and are related.

**Comment by Betree** [comment]
This one is normally fixed with https://github.com/opencollective/opencollective-frontend/pull/7463 (I think this issue and https://github.com/opencollective/opencollective/issues/5202 are the same). Closing but feel free to re-open if you spot it again
