### ISSUE TITLE
Policy should not block Host admins from submitting expenses

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5282]
Currently, when a Collective ticks the policy for "Only allow expenses to be created by Team Members and Financial Contributors" it blocks Host admins from creating expenses too. Host admins should always be able to create expenses in their Collectives.

(At least, this what I think is going on that's blocking me from submitting an expense to [this Collective](https://opencollective.com/chicagolandwarehousefund))

Also, platform admins should also be exempt from this policy restriction.

**Comment by alanna** [comment]
@Betree @znarf could this be done quickly? Or what should I do? I have to submit an expense to this Collective and I can't.

**Comment by alanna** [comment]
@Betree @znarf can this please be done or can it at least be unlocked for platform admins? I need to add an expense to a Collective and I'm blocked.

**Comment by Betree** [comment]
@alanna This should already be resolved by https://github.com/opencollective/opencollective-api/pull/7320

**Comment by alanna** [comment]
OK it would have been nice to be informed! Thanks.

**Comment by alanna** [comment]
This still isn't working for me. I can't submit an expense.
![Screen Shot 2022-03-28 at 8 22 54 PM](https://user-images.githubusercontent.com/5498878/160347032-dd7dccd5-e7ae-4ff3-a8ac-49e18656cad2.png)

**Comment by znarf** [comment]
@Betree @alanna I didn't have this issue in mind when working on the API.

Seems there is also a need for a Frontend side fix.

**Comment by alanna** [comment]
I still can't submit the expense
![Screen Shot 2022-03-29 at 10 26 13 AM](https://user-images.githubusercontent.com/5498878/160490096-d3c6ce80-d573-4126-809d-1f950f8bd8e6.png)

**Comment by alanna** [comment]
this is working now
