### ISSUE TITLE
Check FromCollective of new Orders

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#604]
When WWCode host adds money to a collective, it's by default coming from her personal Collective, rather than the Host Collective. 

1. Make sure that Add Funds always come from Host account.

2. Check if this will be an issue for any other type of money coming in? Donations (like in FB's case). Do we have a UI to specify where you want the money to come from?

**Comment by asood123** [comment]
See order 5810 and 5813 for recent examples

**Comment by piamancini** [comment]
fixed in new v2

**Comment by asood123** [comment]
This bug is still happening. I see another 22 orders that are from the wrong user (wwcode user c9814, instead of wwcode org c9804)

**Comment by piamancini** [comment]
@clarete this might be relevant for the open collective payment method you are looking into. Please close otherwise.

**Comment by clarete** [comment]
Unfortunately, I don't think we'd be able to attend this request because LibreJS isn't really compatible with our use of Webpack. The whole frontend is compiled into a huge file that will always be categorized as "NONTRIVIAL" by LibreJS.

Nevertheless, I still think it could be great to track the licenses of the packages that we use. A veeeery quick analysis of our API dependencies shows that from our 1386 dependencies (including different versions of the same package if they exist). From that 1072 are `MIT`, there's a bunch of `BSD`s and some very few GPL so most of it is libre software but almost none is copyleft.

I'll create an issue to verify what is the `*` in some licenses and why we depend on any proprietary licenses (Even Stripe is MIT) so I think we might actually be close to 100% free software as well!

Here's the breakdown of what we currently have in the API:

```
{'(BSD-2-Clause OR MIT OR Apache-2.0)': 2,
 '(GPL-2.0 OR MIT)': 1,
 '(MIT AND CC-BY-3.0)': 1,
 '(MIT AND Zlib)': 1,
 '(WTFPL OR MIT)': 1,
 'Apache-2.0': 23,
 'BSD': 9,
 'BSD*': 25,
 'BSD-2-Clause': 26,
 'BSD-3-Clause': 62,
 'BSD-3-Clause OR MIT': 1,
 'Custom': 1,
 'Custom: http://graphql.org/': 2,
 'Custom: http://graphql.org/swapi-graphql': 1,
 'Custom: http://linuxcommand.org/man': 1,
 'Custom: https://flowtype.org/': 2,
 'Custom: https://github.com/dominictarr/event-stream': 1,
 'Custom: https://github.com/douglascrockford/JSON-js': 1,
 'Custom: https://github.com/graphql/graphql-language-service': 2,
 'GPL-3.0': 2,
 'ISC': 109,
 'LGPL': 1,
 'LicenseRef-LICENSE': 1,
 'MIT': 1072,
 'MIT*': 24,
 'Public Domain': 1,
 'UNKNOWN': 2,
 'UNLICENSED': 1,
 'Unlicense': 2,
 'WTFPL': 1,
 'license': 1,
 'proprietary': 1}
```

I'll close this issue and then I'll create another one to trace what proprietary software we're using and why!

**Comment by clarete** [comment]
I'm closing this one until we have another relevant event.
