### ISSUE TITLE
user can't pay expense

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#738]
no approve button shows up. Same case as #686 and #727?
URL https://opencollective.com/indieweb/expenses

![screenshot 2017-12-06 11 55 56](https://user-images.githubusercontent.com/3671070/33682537-c7db803c-da95-11e7-8d4e-1905983f8923.png)

Thank you for taking the time to report an issue 

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by asood123** [comment]
Fixed.

**Comment by JeanPaulGrange** [comment]
Hello,
It is not solved : see #727 at this address : https://opencollective.com/reconomycop#budget

**Comment by JeanPaulGrange** [comment]
Hi Pia,

Very strange because I still have that :

[image: Images intégrées 1]

Amitiés,
Jean-Paul Grange
 www.set94.org - www.val-de-marne-en-transition.org -
www.transitionparisidf.org -  www.transitionfrance.fr


2018-01-02 18:44 GMT+01:00 Pia Mancini <notifications@github.com>:

**Comment by piamancini** [comment]
@JeanPaulGrange can you upload the attachment again? I can't see it. thanks!

**Comment by JeanPaulGrange** [comment]
Amitiés,
Jean-Paul Grange
 www.set94.org - www.val-de-marne-en-transition.org -
www.transitionparisidf.org -  www.transitionfrance.fr


2018-01-02 20:01 GMT+01:00 Pia Mancini <notifications@github.com>:
